name: CI/CD

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v3
        - name: Build Docker image
          run: docker build . -f Dockerfile -t pokedex
        - name: Run docker image
          run: |
            docker run -d -p 4200:80 --name pokedex pokedex
        - name: Wait for container to start
          run: sleep 5
        - name: Curl test
          run: |
            curl http://0.0.0.0:4200
            docker stop pokedex