name: CI/CD

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v3
        - name: Build Docker image
          run: docker build . --file Dockerfile --tag pokedex:$(date +%s)

        - name: Test Docker image
          run: |
            docker run -d -p 4200:80 --name pokedex pokedex
            curl http://localhost:8080
            docker stop pokedex