name: Deploy CI

on:
  push:
    tags:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2 

    - name: Deploy
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
      with:
        build_configuration: development
        deploy_branch: gh-pages
        base_href: /esgi-cicd-exam/
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        angular_dist_build_folder: dist/pokedex

